//Types for TOURNAMENT

export const GET_ERRORS = "GET_ERRORS";
export const GET_TOURNAMENTS = "GET_TOURNAMENTS";
export const GET_TOURNAMENT = "GET_TOURNAMENT";
export const DELETE_TOURNAMENT = "DELETE_TOURNAMENT";

//Types for MATCHES

export const GET_TOURNAMENT_MATCHES = "GET_TOURNAMENT_MATCHES";
export const GET_MATCH = "GET_MATCH";
export const DELETE_MATCH = "DELETE_MATCH";

//Types for PLAYERS

export const GET_NEW_PLAYER = "GET_NEW_PLAYER";
export const GET_PLAYER = "GET_PLAYER";
export const GET_PLAYERS = "GET_PLAYERS";
export const GET_UNREGISTERED = "GET_UNREGISTERED";

//Types for SECURITY

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_CURRENT_PLAYER = "GET_CURRENT_PLAYER";
export const GET_CURRENT_PLAYER_MATCHES = "GET_CURRENT_PLAYER_MATCHES";